spring.application.name=GrankinTgBot
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=anzam
spring.datasource.password=d95e8258f
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.jdbc.dialect=postgresql
spring.liquibase.enabled=false
spring.jpa.hibernate.ddl-auto=create-drop